[workspace]
authors = ["Ramiro Harguinteguy <ramirohar@gmail.com>"]
channels = ["https://repo.prefix.dev/conda-forge","conda-forge"]
name = "MatplotTemplate"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "*"
matplotlib = "*"
ipykernel = ">=6.30.1,<7"
opencv = ">=4.12.0,<5"
py-opencv = ">=4.12.0,<5"
pygame = ">=2.6.1,<3"
scikit-image = ">=0.25.2,<0.26"
pillow = ">=11.3.0,<12"
pandas = ">=2.3.2,<3"
scipy = ">=1.16.2,<2"
